#!/usr/bin/python


from git import validate_flow_initialized
from git import format_blanks
from git import redeem
from sys import argv, exit
from git import GitError


def usage(): print("""
  Applies on RELEASE branch.
  
  Aborts if RELEASE branch doesn't have tags 
  'waiting for approval' otherwise it removes it
  and deletes 'branch/released' tag from branch.
""")


if len(argv) > 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit(format_blanks('Invalid option'))

try:
    validate_flow_initialized()
    success_msg = redeem()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
