#!/usr/bin/python


from git import validate_branch
from git import validate_repository
from git import dev_test
from sys import argv, exit
from git import GitError


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Adds tag 'branch/testing' to the last commit of branch.
  
  Makes patch from tag 'branch/started' to 'branch/testing'
  and applies it to DEVELOP branch if no test is in 
  progress.
""")


if len(argv) > 2:
    exit('  Invalid number of arguments.')

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit('  Invalid option')

try:
    validate_branch()
    validate_repository()
    dev_test()

except GitError as ex:
    exit(ex.value)
