#!/usr/bin/python

def usage(): print(
"""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Adds tag 'branch/finished' on last commit of branch
  and reverts active test commit on DEVELOP with sufix 
  /success, if exists.
""")

from git import validate_repository
from git import validate_branch
from git import git_finish
from sys import argv, exit
from git import GitError

if len(argv) > 2:
	exit('  Invalid number of arguments.')
	
elif 'help' in argv:
	usage()
	exit()
	
elif len(argv) == 2:
	exit('  Invalid option')
	
try:
	validate_branch()
	validate_repository()
	git_finish()

except GitError as ex:
	exit(ex.value)