#!/usr/bin/python

def usage(): print(
"""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Aborts if RELEASE branch has tags 'waiting for approval'
  or 'waiting for overall approval'.
  
  If 'branch/finished' exists on last commit of branch,
  adds tag 'branch/released' on the same commit and makes 
  a patch from 'branch/started' to 'branch/released' which
  is applied onto RELEASE branch and committed with message
  'branch'
""")

from git import validate_repository
from git import validate_branch
from git import git_release
from sys import argv, exit
from git import GitError

if len(argv) > 2:
	exit('  Invalid number of arguments.')
	
elif 'help' in argv:
	usage()
	exit()
	
elif len(argv) == 2:
	exit('  Invalid option')
	
try:
	validate_branch()
	validate_repository()
	git_release()

except GitError as ex:
	exit(ex.value)