#!/usr/bin/python


from git import validate_repository
from git import create_new_feature_branch
from sys import argv, exit
from git import GitError


def usage(): print("""
  Creates new FEATURE branch from STABLE branch,
  with name formatted to FEATURE/name.
""")


if len(argv) == 1 or len(argv) > 2:
    exit('  Need to specify name of the branch.')

elif 'help' in argv:
    usage()
    exit()

feature_name = argv[1]

if '.' in feature_name:
    exit("  %s is not a valid branch name." % feature_name)

try:
    validate_repository()
    success_msg = create_new_feature_branch(feature_name)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
