#!/usr/bin/python


from git import validate_flow_initialized
from git import validate_branch
from git import format_blanks
from git import release
from sys import argv, exit
from git import GitError


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Aborts if RELEASE branch has tags 'waiting for approval'
  or 'waiting for overall approval'.
  
  If 'branch/finished' exists on last commit of branch,
  adds tag 'branch/released' on the same commit and makes 
  a patch from 'branch/started' to 'branch/released' which
  is applied onto RELEASE branch and committed with message
  'branch'
""")


if len(argv) > 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit(format_blanks('Invalid option'))

try:
    validate_branch()
    validate_flow_initialized()
    success_msg = release()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
