#!/usr/bin/python


from git import validate_flow_initialized
from git import create_new_junk_branch
from git import format_blanks
from sys import argv, exit
from git import GitError


def usage(): print("""
  Creates new JUNK branch from current branch,
  with name formatted to JUNK/name.
""")


if len(argv) != 2:
    exit(format_blanks('Need to specify name of the branch.'))

elif 'help' in argv:
    usage()
    exit()

junk_name = argv[1]

if '.' in junk_name:
    exit(format_blanks('%s is not a valid branch name.' & junk_name))

try:
    validate_flow_initialized()
    success_msg = create_new_junk_branch(junk_name)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
