#!/usr/bin/python


from git import validate_repository
from git import validate_branch
from git import prolong
from sys import argv, exit
from git import GitError


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Removes tag 'branch/testing' if exists, otherwise
  aborts.
""")


if len(argv) > 2:
    exit('  Invalid number of arguments.')

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit('  Invalid option')

try:
    validate_branch()
    validate_repository()
    prolong()

except GitError as ex:
    exit(ex.value)
