#!/usr/bin/python

def usage(): print(
"""
  Applies on RELEASE branch.
  
  Aborts if RELEASE branch doesn't have tags 
  'waiting for approval' or 'waiting for overall approval',
  otherwise it removes them.
""")

from git import validate_repository
from git import validate_branch
from git import git_approve
from sys import argv, exit
from git import GitError

if len(argv) > 2:
	exit('  Invalid number of arguments.')
	
elif 'help' in argv:
	usage()
	exit()
	
elif len(argv) == 2:
	exit('  Invalid option')
	
try:
	validate_branch()
	validate_repository()
	success_msg = git_approve()
	print(success_msg)
	
except GitError as ex:
	exit(ex.value)