#!/usr/bin/python


from git import validate_repository
from git import validate_branch
from git import release
from sys import argv, exit
from git import GitError


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Aborts if RELEASE branch has tags 'waiting for approval'
  or 'waiting for overall approval'.
  
  If 'branch/finished' exists on last commit of branch,
  adds tag 'branch/released' on the same commit and makes 
  a patch from 'branch/started' to 'branch/released' which
  is applied onto RELEASE branch and committed with message
  'branch'""")


if len(argv) > 2:
    exit('  Invalid number of arguments.')

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit('  Invalid option')

try:
    validate_branch()
    validate_repository()
    release()

except GitError as ex:
    exit(ex.value)
