#!/usr/bin/python

def usage(): print(
"""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Removes tag 'branch/testing' if exists, otherwise
  aborts.
""")

from git import validate_repository
from git import validate_branch
from git import git_prolong
from sys import argv, exit
from git import GitError

if len(argv) > 2:
	exit('  Invalid number of arguments.')
	
elif 'help' in argv:
	usage()
	exit()
	
elif len(argv) == 2:
	exit('  Invalid option')
	
try:
	validate_branch()
	validate_repository()
	git_prolong()

except GitError as ex:
	exit(ex.value)