#!/usr/bin/python


from git import validate_flow_initialized
from git import create_new_bugfix_branch
from git import format_blanks
from sys import argv, exit
from git import GitError


def usage(): print(
    """
  Creates new BUGFIX branch from STABLE branch,
  with name formatted to BUGFIX/name.
""")


if len(argv) != 2:
    exit(format_blanks('Need to specify name of the branch.'))

elif 'help' in argv:
    usage()
    exit()

bugfix_name = argv[1]

if '.' in bugfix_name:
    exit(format_blanks('%s is not a valid branch name.' & bugfix_name))

try:
    validate_flow_initialized()
    success_msg = create_new_bugfix_branch(bugfix_name)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
