#!/usr/bin/python


from git import validate_flow_initialized
from git import format_blanks
from git import format_commit
from sys import argv, exit
from git import GitError


def usage(): print("""
  Format commit message as branch_name/commit_msg and makes
  commit of staged files.
""")


if len(argv) != 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

commit_msg = argv[1]

try:
    validate_flow_initialized()
    format_commit(commit_msg)

except GitError as ex:
    exit(ex.value)
