#!/usr/bin/python


from sys import argv, exit

from git import GitError
from git import format_blanks
from git import start_flow_initialization


def usage(): print("""
  Initialize main branches of corvus git workflow.

  Arguments specify root branch and starting version.
  Root branch name must not contain char '.' while 
  version must contain at least one.
  
  If omitted, root branch will be set to current branch,
  also if omitted version will be set to 1.0.0
""")


version = ''

if len(argv) != 2:
    exit(format_blanks('Invalid number of arguments: missing starting version'))

elif 'help' in argv:
    usage()
    exit()

version = argv[1]

try:
    if version == '':
        exit(format_blanks('Starting version must be provided (eg. 1.0.0)'))

    print(format_blanks('Initialization...'))
    success_msg = start_flow_initialization(version)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
