#!/usr/bin/python


from sys import argv, exit

from git import GitError
from git import create_new_feature_branch
from git import format_blanks
from git import validate_flow_initialized


def usage(): print("""
  Creates new FEATURE branch from STABLE branch,
  with name formatted to FEATURE/name.
""")


if len(argv) != 2:
    exit(format_blanks('Need to specify name of the branch.'))

elif 'help' in argv:
    usage()
    exit()

feature_name = argv[1]

if '.' in feature_name:
    exit(format_blanks('%s is not a valid branch name.' % feature_name))

try:
    validate_flow_initialized()
    success_msg = create_new_feature_branch(feature_name)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
