#!/usr/bin/python


from sys import argv, exit

from git import GitError
from git import dev_test
from git import format_blanks
from git import validate_branch
from git import validate_flow_initialized


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Adds tag 'branch/testing' to the last commit of branch.
  
  Makes patch from tag 'branch/started' to 'branch/testing'
  and applies it to DEVELOP branch if no test is in 
  progress.
""")


if len(argv) > 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit(format_blanks('Invalid option'))

try:
    validate_branch()
    validate_flow_initialized()
    success_msg = dev_test()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
