#!/usr/bin/python

from sys import argv, exit
from modules.git_core import GitError
from modules.git_flow import prolong
from modules.git_format import format_blanks
from modules.git_validation import validate_branch
from modules.git_validation import validate_flow_initialized


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Removes tag 'branch/testing' if exists, otherwise
  aborts.
""")


if len(argv) > 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit(format_blanks('Invalid option'))

try:
    validate_flow_initialized()
    success_msg = prolong()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
