#!/usr/bin/python

from sys import argv, exit
from modules.git_core import GitError
from modules.git_flow import finish
from modules.git_format import format_blanks
from modules.git_validation import validate_flow_initialized


def usage(): print("""
  Applies on HOTFIX, BUGFIX and FEATURE branches.
  
  Adds tag 'branch/finished' on last commit of branch
  and reverts active test commit on DEVELOP with sufix 
  /success, if exists.
""")


if len(argv) > 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

elif len(argv) == 2:
    exit(format_blanks('Invalid option'))

try:
    validate_flow_initialized()
    success_msg = finish()
    print(success_msg)

except GitError as ex:
    exit(ex.value)
