#!/usr/bin/python

from sys import argv, exit
from modules.git_core import GitError
from modules.git_flow import create_new_hotfix_branch
from modules.git_format import format_blanks
from modules.git_validation import validate_flow_initialized


def usage(): print("""
  Creates new HOTFIX branch from PROD branch,
  with name formatted to HOTFIX/name.
""")


if len(argv) != 2:
    exit(format_blanks('Need to specify name of the branch.'))

elif 'help' in argv:
    usage()
    exit()

hotfix_name = argv[1]

if '.' in hotfix_name:
    exit(format_blanks('%s is not a valid branch name.' % hotfix_name))

try:
    validate_flow_initialized()
    success_msg = create_new_hotfix_branch(hotfix_name)
    print(success_msg)

except GitError as ex:
    exit(ex.value)
