#!/usr/bin/python

from sys import argv, exit
from modules.git_core import GitError
from modules.git_format import format_blanks
from modules.git_flow import commit_with_prefix
from modules.git_validation import validate_flow_initialized


def usage(): print("""
  Format commit message as branch_name/commit_msg and makes
  commit of staged files.
""")


if len(argv) != 2:
    exit(format_blanks('Invalid number of arguments.'))

elif 'help' in argv:
    usage()
    exit()

commit_msg = argv[1]

try:
    validate_flow_initialized()
    commit_with_prefix(commit_msg)

except GitError as ex:
    exit(ex.value)
